In [2]:
import pandas as pd
import numpy as np

In [31]:
loc = 'D:\BDS DOCS\Year 1\Internship\Covid Data\Zonewise_Data_COVID19.csv'

In [32]:
df = pd.read_csv(loc)

In [33]:
df

,Sno,District,State,Category,District_level_Infected,Deaths,Total number of Primary Health Centres,Total number of Community Health Centres,Total number of Subdivisional Hospitals,Total number of Divisional Hospitals
0,1,Leh(ladakh),Jammu & Kashmir,Green,34,0,16.0,3.0,0.0,1.0
1,2,Kargil,Jammu & Kashmir,Red,12,0,16.0,4.0,0.0,1.0
2,3,Kupwara,Jammu & Kashmir,Red,147,0,17.0,7.0,0.0,1.0
3,4,Bandipore,Jammu & Kashmir,Yellow,140,1,13.0,3.0,0.0,1.0
4,5,Baramula,Jammu & Kashmir,Red,128,4,32.0,6.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
712,713,Jayashankar,Telangana,Yellow,5,0,NaN,NaN,NaN,NaN
713,714,Jogulamba,Telangana,Yellow,45,1,0.0,1.0,1.0,0.0
714,715,Kamareddy,Telangana,Yellow,12,0,0.0,6.0,2.0,0.0
715,716,Karimnagar,Telangana,Yellow,19,0,0.0,3.0,0.0,1.0
716,717,Khammam,Telangana,Yellow,8,0,0.0,3.0,0.0,1.0

In [34]:
states = df['State'].unique()

In [35]:
reds = []
greens = []
yellows = []

for state in states:
    temp = df[df['State'] == state]
    red = temp[temp['Category'] == 'Red'].__len__()
    green = temp[temp['Category'] == 'Green'].__len__()
    yellow = temp[temp['Category'] == 'Yellow'].__len__()
    reds.append(red)
    greens.append(green)
    yellows.append(yellow)

In [38]:
data = {'State': states,
       'Red': reds,
       'Yellow': yellows,
       'Green': greens}

In [39]:
df = pd.DataFrame(data)

In [40]:
df['Total'] = df['Red'] + df['Yellow'] + df['Green']

In [41]:
df['Red(%)'] = (df['Red'] * 100) / df['Total']  
df['Yellow(%)'] = (df['Yellow'] * 100) / df['Total']  
df['Green(%)'] = (df['Green'] * 100) / df['Total']

In [43]:
df.to_csv('D:\BDS DOCS\Year 1\Internship\Covid Data\Zonewise_Percentage_Data_COVID19.csv', index=False)