# Objective

Uses the state_wise_daily dataset, which is in the form of time series data and converts it into a more manageble form

# Importing the packages

In [1]:
import numpy as np
import pandas as pd

# Importing the dataset

In [2]:
df = pd.read_csv('D:/BDS Docs/Year 1/Internship/Covid Data/state_wise_daily.csv')

In [3]:
df

,Date,Status,TT,AN,AP,AR,AS,BR,CH,CT,...,PB,RJ,SK,TN,TG,TR,UP,UT,WB,UN
0,14-Mar-20,Confirmed,81,0,1,0,0,0,0,0,...,1,3,0,1,1,0,12,0,0,0
1,14-Mar-20,Recovered,9,0,0,0,0,0,0,0,...,0,1,0,0,0,0,4,0,0,0
2,14-Mar-20,Deceased,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15-Mar-20,Confirmed,27,0,0,0,0,0,0,0,...,0,1,0,0,2,0,1,0,0,0
4,15-Mar-20,Recovered,4,0,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,02-Jun-20,Recovered,4531,0,40,0,53,62,0,9,...,17,222,0,536,35,0,146,30,104,0
242,02-Jun-20,Deceased,221,0,0,0,0,1,1,0,...,2,4,0,13,4,0,7,2,10,0
243,03-Jun-20,Confirmed,9638,0,180,10,271,230,0,64,...,34,279,1,1286,129,102,141,42,340,709
244,03-Jun-20,Recovered,3786,0,50,0,76,222,0,40,...,12,309,0,610,30,0,81,7,170,0
245,03-Jun-20,Deceased,259,0,4,0,0,1,0,0,...,1,6,0,8,7,0,1,1,10,0

# Transforming the dataset into a more structured dataset

In [4]:
unique_states = list(df.columns)[2:] # getting the list of states
unique_dates = df['Date'].unique() # getting the dates

In [5]:
"""
Storing the number of confirmed, recovered and deceased cases in each state in a list.
"""
cases = []
# cases.shape
for state in unique_states:
    case = df[state].values.reshape(-1,3)
    cases.append(case)
cases = np.array(cases)

In [6]:
new_cases = cases[0]
for case in cases[1:]:
    new_cases = np.append(new_cases, case, axis=1)
cases = new_cases.reshape(1, (new_cases.shape[1]//3)*new_cases.shape[0], 3)[0]

# Creating a Dataframe

In [7]:
dates = []
states = []
for date in unique_dates:
    for state in unique_states:
        dates.append(date)
        states.append(state)
confirmed = cases[:, 0]
recovered = cases[:, 1]
deceased = cases[:, 2]

In [8]:
df2 = pd.DataFrame({'Date': dates,
                    'State': states,
                    'Confirmed': confirmed,
                    'Recovered': recovered,
                    'Deceased': deceased                    
})

# Exporting the dataframe

In [9]:
df2.to_csv('D:/BDS Docs/Year 1/Internship/Covid Data/state_wise_daily_ts.csv', index=False, header=True, mode='w')